code/extensions/FluentSiteTree.php

Current code does not take into account the Subsite module. The baseUrl should be the one of the owner subsite if it exists.

Subsite support for urlsegment

---

javascript/fluent.js

- Moved `urlForLocale` so it’s not bound to a selector, changed it to accept a URL as an argument rather than assume `document.location.href` is the URL in question;
- Updated `$(".cms-fluent-selector .cms-fluent-selector-locales a").onclick()` to reflect new `urlForLocale` logic;
- Added `$('.cms-panel-deferred').onadd()` to add the fluent locale parameter to the deferred URL
I initially tried just disabling the deferred panels from ever being cached, but I think this is a better approach as it keeps that caching in-place. It’s not specific to the CMS tree view (#94 is the issue I’m trying to fix), but I don’t think that matters.

FIX: Ensure deferred CMS panels are locale-specific (fixes #94)

---

code/extensions/FluentExtension.php
tests/FluentTest.php

It might be useful for some people to use a language alias in some cases. I have added `LanguageAlias` to the data returned by `LocaleInformation` so a user can easily use it in a custom template.

Adding LanguageAlias to LocaleInformation data

---

code/extensions/FluentExtension.php

Fixed an issue where deleting all text in a translated field and saving the object did not update the locale field in the DB. Fixes #204

FIX: $manipulation updated for empty fields

---

code/extensions/FluentFilteredExtension.php

Hey Damian,
This is just optional - thought it might make it easier in situations where you might only need to check if an object is visible in the current locale, e.g.:
```php
foreach ($relations as $object) {
if (!$object->hasExtension('FluentFilteredExtension') || $object->canViewInLocale()) {
// use it
}
}
```
As opposed to `$object->canViewInLocale(Fluent::current_locale())`

Add default fallback to current locale to canViewInLocale

---

code/extensions/FluentExtension.php
lang/en.yml

Uses a success message state for the default locale, or a notice state for a non-default locale.
Is translatable.
Default locale:
Non-default locale:
Resolves #221

Add visual UI indicator for whether you are editing in the default locale or not

---

code/extensions/FluentExtension.php

Fixes an issue that was introduced with #221 
When the `updateCMSFields` extension hook is called multiple times (eg. once in a base-class and once in a superclass), the message would be added for every `extend` call.
This PR introduces a check that ensures that the message only gets added once.
Also made the method API more consistent.

Fix addLocaleIndicatorMessage method to only add locale message once.

---

src/Control/LocaleAdmin.php
src/Middleware/DetectLocaleMiddleware.php
src/Model/Locale.php
src/State/LocaleDetector.php
tests/php/Middleware/DetectLocaleMiddlewareTest.php
tests/php/Middleware/DetectLocaleMiddlewareTest.yml
tests/php/Model/LocaleTest.php

Order should be 1) route param, 2) request param, 3) persisted locale and if home page then 4) language header.

NEW Ensure locale detection priority is honoured for homepage and non-homepage routes

---

_config/cms.yml
src/Extension/FluentChangesExtension.php
src/Extension/FluentExtension.php
src/Extension/FluentVersionedExtension.php

This required a few core extension points (won't work on beta4, but will on rc1).
When we unpublish this ensures that the current locale is unpublished, but no other locales.
The "root" table is always unpublished after the last localised version is unpublished.
cc @robbieaverill

BUG Ensure that unpublish affects only the current locale

---

.scrutinizer.yml

Fixes the issue caused by outdated composer version
```
- silverstripe/vendor-plugin 1.0.1 requires composer-plugin-api ^1.1 -> no matching package found.
```

Update scrutinizer build

---

src/Extension/FluentExtension.php
src/Extension/FluentSiteTreeExtension.php
tests/php/Extension/FluentExtensionTest.php
tests/php/Extension/FluentSiteTreeExtensionTest.php
tests/php/Extension/FluentSiteTreeExtensionTest.yml
tests/php/Extension/Stub/FluentStubObject.php
tests/php/Middleware/DetectLocaleMiddlewareTest.php
tests/php/Middleware/InitStateMiddlewareTest.php
tests/php/Middleware/Stub/DetectLocaleMiddlewareSpy.php
tests/php/Model/LocaleTest.php

Migrated from old 3 branch, along with various tests and cleanup to the (awesome) tests that are already there. :)
For @robbieaverill to review

Tests for FluentSiteTreeExtension::Link()

---

src/Extension/FluentExtension.php

This addition makes the assumption that Fluent (by default) wants unpublished locales to inherit and display data based on its "Fallback", and for that data to be visible on the frontend (the same as current CMS/backend functionality). Unpublished locales are only hidden on the frontend when/if this config variable is set on the `owner` Object.
I would be more than happy to flip this assumption to hide on frontend by default if that is preferred.

Add new config to determine frontend visibility of unpublished locales

---

lang/en.yml
src/Extension/FluentFilteredExtension.php
src/Extension/FluentSiteTreeExtension.php

Since these messages are designed for content authors, I think they should be lowercased. Page and Locale (if referring to class names) would be for developers.

FIX Use lowercase for page and locale in content author messages

---

src/Middleware/DetectLocaleMiddleware.php

Fluent is great for changing CMS edited content to a different locale per request.
However this does not alter all the template and PHP managed translation such as
FormField labels, or template controlled headings. This leads to odd end user
experiences where someone may be viewing the German content, and have it labelled
by English. This fix sets the i18n class locale to the same as the requested one
used by Fluent to give a consistent and far less confusing experience. This is
limited to the 'front end' (non CMS) site as e.g. it is feasible that a content
editor in Germany who is fluent in English would want the interface to remain in
German.
Resolves #327

ENHANCEMENT: Set SS locale to match requested one

---

docs/en/configuration.md
docs/en/domain-configuration.md
docs/en/migrating-from-translatable.md
readme.md
src/Task/ConvertTranslatableTask.php
src/Task/ConvertTranslatableTask/Exception.php

To run this task, ensure you have updated your system to SS4, run a dev/build
and added the locales you need to use in the CMS Locale interface. Next run
the build task, which will write and/or publish your content via the Fluent
ORM, then clean up the old Translatable tables and extra columns.
This task is based on the existing task from SS3.
Part of #328

NEW Add task to convert SS3 Translatable data to SS4 Fluent

---

src/Extension/FluentSiteTreeExtension.php

NEW Use Bootstrap alert class in locale status message

---

lang/en.yml
src/Extension/FluentSiteTreeExtension.php

Changes were made to indicate that locale not visible until it is published, as well as the translations updated via the TextCollector task:
An 'invisible eye' icon still needs to be added at some stage.
Related to #311 
Reference: https://projects.invisionapp.com/share/ZBFVZJCKU38#/screens/279729292_X_Fluent

ENHANCEMENT Update bootstrap alert 

---

src/Search/FluentSearchVariant.php

In order to be able to search content, we must first be able to add it
to the index. To add the content in each locale (which can vary) we must
support a Variant, much like that of the `Versioned` module. Fluent
itself takes care of modifying the query to select content, we just must
allow the Reindex task to attain and adjust it's settings.
Resolves #335

ENHANCEMENT Support fulltext search per locale

---

src/Extension/FluentSiteTreeExtension.php
tests/php/Extension/FluentSiteTreeExtensionTest.php

Fixes #367
Instead of inlining this logic, dummy frontend + domain mode, and join absolutebase + parentrelative together.
Less string comparison = more robust. :)

BUG Fix urlsegment field

---

src/Search/FluentSearchVariant.php

Fixes an issue where the Variant applies `_locale` to queries but not the index.

Only apply query change when `Locale::getCached()->count()` is true

---

src/Middleware/DetectLocaleMiddleware.php

We have two components to our websites: the marketing website which runs on [www.](https://www.royalalberthall.com/tickets/events/2018/nine-inch-nails/) and the purchase path which runs on [tickets.](https://tickets.royalalberthall.com/booking/production/bestavailable/60640)
The marketing site needs to set the cookie so that the tickets. domain has access to it, which is a problem because the module will only set the persist cookie on the current domain.
Two options to get around this is set cookie to be set on domain without the subdomain i.e. `.example.com` but that's not really required if we just allow the cookie domain to be set, which is option two.
The PR exposes two variables which will let the user specify the path using `persist_cookie_path` and domain using …

Allow cookie domain and path to be configurable

---

templates/Wilr/GoogleSitemaps/Control/GoogleSitemapController_sitemap.ss

Google reports invalid date format on generated sitemaps.
Changing to the rfc3339 format, including the timezone offset cure the problem.
(This has already been included in the standard sitemaps addon)

Update date format in sitemap template

---

src/Model/Domain.php

On SS 4.1.0 returning a string in this GridField summary field throws an exception. Instead, we should cast it as a DBField.
Resolves #380

FIX Cast default locale title as a DBField to prevent search field scaffolding error

---

composer.json

Although inconsequential, the current constraints are all marked as dev - an overhang from when SilverStripe 4 was in pre-release stages. This is no longer necessary, so we can remove them in order to keep the constraints more in line with other modules (such as the requirements here) and easier to read.

Update composer requirement constraints

---

src/Extension/FluentExtension.php

I have found that the `getLocalisedTables()` method is incredibly useful for some of the project specific *oddities* that we've been adding. Can we please make it public so that I don't have to duplicate the logic elsewhere?

Change getLocalisedTables method to public.

---

_config/model.yml
src/Extension/FluentExtension.php

Fixes #406
Replacement solution for https://github.com/tractorcow/silverstripe-fluent/pull/407
Instead of adding the config via extension (which cannot be easily overridden on a model by model basis via yml) add the default config via yml.
@dhensby I think this might be a better convention going forward; Promote use of yml for configs, rather than adding private statics to extension classes. What is your feeling on this?

ENHANCEMENT Shift extension default to yml file to promote better extensibility

---

src/Extension/FluentExtension.php
tests/php/Extension/FluentExtensionTest.php
tests/php/Extension/FluentExtensionTest.yml
tests/php/Extension/FluentExtensionTest/LocalisedParent.php

WIP: FIX Implement localisable order by clause to support translatable sorting

---

src/Search/FluentSearchVariant.php

Follow up on https://github.com/tractorcow/silverstripe-fluent/pull/450
This supports older versions, since we don't mandate fulltextsearch 3.3 as a requirement.

FIX Ensure alterQuery is compatible with silverstripe/fulltextsearch <3.3

---

src/Extension/FluentSiteTreeExtension.php
src/Model/FallbackLocale.php
tests/php/Extension/FluentSiteTreeExtensionTest.php

Added back a message that was accidentally removed in #361.
When `frontend_publish_required` is set to false, there is the possibility that content in being inherited from another locale.
We could add further checks for content inheritance to make these message more specific, but I thought that would be overkill. A simple "may/may-not" message felt sufficient.
Not published, not drafted:
Not published, drafted:
Added a docblock to `FallbackLocale`.

v4: ENHANCEMENT Update CMS localisation status messages.

---

_config.php
code/Fluent.php

Ensure compatibility with PHP 7.2 ("object" is a reserved word), with SilverStripe 3.6 (using Object) and SilverStripe 3.7 (using SS_Object)

3.8:  Make Fluent compatible to SilverStripe 3.7.x / PHP 7.2 

---

_config/model.yml
src/Extension/FluentExtension.php
tests/php/Extension/FluentSiteTreeExtensionTest.php

We currently have this logic sitting in project code through an extension, and I'm more than happy for it to stay there, but...
Current project relies heavily on `DataObject`s that are managed through a 3rd party system - there is no ability to modify these `DataObject`s in SilverStripe, but they can be viewed and they can be added as relationships on other `DataObject`s.
As such, we have a requirement to hide un-localised `DataObject`s not only on the frontend, but in the CMS as well (so that authors don't add unavailable `DataObject`s as relationships).
Add a config value for `cms_publish_required` so that devs can separately control frontend and CMS visibility options.

v4: Proposal to add config setting for CMS publish required.

---

_config/model.yml
src/Extension/FluentFilteredExtension.php
tests/php/Extension/FluentFilteredExtensionTest.php

I wasn't too sure if we wanted the default set to `true` or `false`. Having it as `true` by default leaves functionality the same as it is atm. Maybe next major release we could change that.

v4: Added config setting to bypass filtered locale logic in stage. Fixes #461

---

tests/php/Extension/FluentBadgeExtensionTest.php
tests/php/Extension/FluentExtensionTest.php
tests/php/Extension/FluentFilteredExtensionTest.php
tests/php/Extension/FluentSiteTreeExtensionTest.php
tests/php/Extension/FluentVersionedExtensionTest.php
tests/php/Middleware/DetectLocaleMiddlewareTest.php

Failing tests are the sorting ones we're already aware of.
Desired outcome is that nothing has changed. Using `withState` just keeps everything nicely in a bubble.
Resolves #462

ENHANCEMENT: Update unit tests to use withState where appropriate. Resolves #462

---

src/Model/Locale.php

This PR caches the call of `Locale::getCached` and keys is by the actual locale title. Calls to `getByLocale` are just an array lookup by key now :+1:.

FIX Performance update - reduces the use of filter on multiple subsequent calls to getByLocale

---

src/Extension/FluentVersionedExtension.php
tests/php/Extension/FluentVersionedExtensionTest.php

This PR adds a static method to pre-populate a cache of object IDs that exist in the given locale. This can be opted into by calling this method from appropriate user-code (or user-code extension) or alternatively by providing a list of classes that should be pre-populated (done when the first call of `isLocalisedInStage` is performed for that class).
Ideally I wouldn't have this config option but it is currently quite difficult to find a location to prepopulate this cache when running the SiteTree, although I'm open to suggestions here and more than happy to remove the configuration part of this PR.
Fixes #467

FIX Opt-in performance fix for many consecutive lookups using isLocalisedInStage

---

.travis.yml
src/Model/CachableModel.php
tests/php/Extension/FluentExtensionTest.php

The sorting tests always pass locally, so I only want to exclude them from Travis builds. I have also added the static $locales_by_title to CacheableModel::clearCache().
This could be improved by renaming the property to something that Locale and Domain both have (a bit more abstract) like $cached_data, but this is a quick patch to get the tests green again.
Fixes the broken PHPUnit tests on 4.1 and fixes https://github.com/tractorcow-farm/silverstripe-fluent/issues/454 by ignoring them in Travis

Exclude sorting tests from Travis builds and clear static locale cache in tests

---

_config/cms.yml
src/Extension/FluentReadVersionsExtension.php
tests/php/Extension/FluentReadVersionsExtensionTest.php

Requires https://github.com/silverstripe/silverstripe-versioned/pull/182
Resolves https://github.com/tractorcow-farm/silverstripe-fluent/issues/414

FIX ReadVersions GraphQL operation now has the current fluent locale added as a filter

---

docs/en/configuration.md
src/Middleware/DetectLocaleMiddleware.php
tests/php/Middleware/DetectLocaleMiddlewareTest.php

It kills any HTTP caching otherwise. The distinction between `is_null` and "empty string" isn't ideal of course.
See https://github.com/tractorcow/silverstripe-fluent/issues/440

Opt-out of cookie and session locale persistence (fixes #440)

---

_config/tests.yml
src/Dev/FluentTestState.php
src/Extension/FluentVersionedExtension.php
src/Middleware/DetectLocaleMiddleware.php
tests/php/Middleware/DetectLocaleMiddlewareTest.php

Reasoning is that all sessions are always started (isStarted() is true after SessionMiddleware is run), but not all sessions eventuate into a session in finalise. This check catches that.

BUG Prevent force-creating empty sessions

---

src/Extension/FluentReadVersionsExtension.php
tests/php/Extension/FluentReadVersionsExtensionTest.php

Prevents breaking when fluent is not enabled, or querying objects that are not fluent

FIX Only updateList for objects that have the FluentVersionedExtension

---

_config/routing.yml

```
PHP Deprecated: Not quoting the scalar "%$TractorCow\Fluent\Middleware\InitStateMiddleware" starting with the "%" indicator character is deprecated since Symfony 3.1 and will throw a ParseException in 4.0 on line 8. in /Users/robbieaverill/dev/ss43/vendor/symfony/yaml/Inline.php on line 357
PHP Deprecated: Not quoting the scalar "%$TractorCow\Fluent\Middleware\DetectLocaleMiddleware" starting with the "%" indicator character is deprecated since Symfony 3.1 and will throw a ParseException in 4.0 on line 9. in /Users/robbieaverill/dev/ss43/vendor/symfony/yaml/Inline.php on line 357
```

FIX Quote Injector service references, will break in Symfony 4

---

docs/en/configuration.md
src/Model/Locale.php
tests/php/Model/LocaleTest.php
tests/php/Model/LocaleTest.yml

* Added check to locale base url generation
* Added tests to cover new default behaviour
* Docs altered
This may be a breaking change
https://github.com/tractorcow-farm/silverstripe-fluent/issues/486

BUGFIX: Display the current domain's default locale url segment in base urls

---

src/Extension/FluentDirectorExtension.php
tests/php/Extension/FluentDirectorExtensionTest.php
tests/php/Extension/FluentDirectorExtensionTest/TestController.php

Fluent's rules are appended to the beginning of Director's rules list this means that the rule that handles routing to `ModelAsController` trumps all other rules in the site.
For example if we're using the slug "us" for the "en_US" locale and we want to have a controller with a rule "en/search//$Action/$ID/$OtherID" that directs to our own controller. Rather than our own controller as expected handling the request `ModelAsController` handles the request instead. This is due to the order of the rules for Fluent when they are added to the rules array in `FluentDirectorExtension`.
This pull request changes the way the rules are merged so the `RootURLController` rules and the `ModelAsController` rules appear just before the `$URLSegment//$Action/$ID/$OtherID` rule. Having the root url's at …

FIX: Fluent rules block other controllers from defining rules on the locale

---

src/Extension/FluentExtension.php
tests/php/Extension/FluentExtensionTest.php
tests/php/Extension/FluentExtensionTest.yml
tests/php/Extension/FluentExtensionTest/MixedLocalisedSortObject.php

This pull request fixes the issue mentioned in #507 in short if the sort columns of a query are a mix of localized and non-localized fields the order will become non-localized fields first then the localized fields. This is caused by how the fields are removed and re-added to the associative array not factoring in the non-localized fields keeping them in order at the start of the query.

BUGFIX: Fixed issue where the sort order of queries would not be maintained

---

src/Extension/FluentBadgeExtension.php
src/Model/Locale.php

This should've been extensible from the beginning, which is why I'm calling this a bug fix.
Fixes #389

FIX Fluent badge labels in the CMS are now able to be modified by extensions

---

src/Model/Locale.php

See the comments since April 2019 on #389. Improves #510.

Use the locale's URLSegment as default badge label

---

src/Extension/FluentSiteTreeExtension.php
tests/php/Extension/FluentSiteTreeExtensionTest.php

Fluent sets the URLSegment field's URLPrefix to be the base domain plus the parent page path including the current locale. When no fluent domains are configured, this defaulted to `Director::absoluteBaseURL()`. This was a bit heavy handed, since it doesn't consider any previous modifications to `SiteTreeURLSegmentField::setURLPrefix()` (e.g. in subsites, where it sets the subsite domain).
I've changed this to use the existing URL prefix instead.
There will still be conflicts if you use subsite domains and fluent domains at the same time, since they represent the same functionality, but that can be documented.
Fixes https://github.com/silverstripe/silverstripe-subsites/issues/416

FIX Fluent now respects existing base URL prefixes in URL segment fields when no fluent domain exists

---

.upgrade.yml

with mappings for all fluent extensions that are still present in SS4
fixes #528

add .upgrade.yml

---

src/Extension/FluentExtension.php

Already exists in `cwp/cwp` but it should be available in `FluentExtension`

Add `$SelectedLanguage` template variable to fluent

---

_config/delete.yml
src/Extension/FluentExtension.php
src/Extension/FluentFilteredExtension.php
src/Extension/FluentVersionedExtension.php
src/Model/Delete/DeleteFilterPolicy.php
src/Model/Delete/DeleteLocalisationPolicy.php
src/Model/Delete/DeletePolicy.php
src/Model/Delete/DeletePolicyFactory.php
src/Model/Delete/DeleteRecordPolicy.php
src/Model/Delete/UsesDeletePolicy.php
tests/php/Model/Delete/DeleteRecordPolicyTest.php
tests/php/Model/Delete/Fixtures/FilteredRecord.php
tests/php/Model/Delete/Fixtures/LocalisedFilteredRecord.php
tests/php/Model/Delete/Fixtures/LocalisedRecord.php
tests/php/Model/Delete/Fixtures/Record.php
tests/php/Model/LocaleTest.php

Hello I am back from the dead. :)
This feature attempts to solve some of the inconsistencies involved with deleting objects; If you have an object that's localised, deleting the record should remove that localisation, but not all others.
Acceptance Criteria:
- When  deleting an object in one locale, it should not delete it from any other locale (unless it's already deleted there).
- After an object has been deleted in all locales the "delete" button deletes the base record.
- Deleting filtered objects should disable this item in the current locale
- Deleting localised objects should delete the localisation for this item in the current locale
- Deleting a localised + filtered object should delete both the localisation, and disable this item in the current locale

ENHANCEMENT Configurable policies for handling the deletion of objects

---

src/Extension/FluentSiteTreeExtension.php
tests/php/Extension/FluentSiteTreeExtensionTest.php

Reverts tractorcow-farm/silverstripe-fluent#523
Resolves https://github.com/tractorcow-farm/silverstripe-fluent/issues/538

Revert "FIX Fluent now respects existing base URL prefixes in URL segment fields when no fluent domain exists"

---

src/Task/ConvertTranslatableTask.php

Missing -> operator in migration task causing fatal error when Locale not found.

Fixed  missing -> operator.

---

composer.json
package.json
readme.md
src/Extension/FluentSiteTreeExtension.php

Updated github links to point to tractorcow-farm. Link to [Issue 75](https://github.com/tractorcow-farm/silverstripe-fluent/blob/master/src/Extension/FluentSiteTreeExtension.php#L83) resulting in 404.

Link to issue 75 returning 404

---

src/Extension/FluentBadgeExtension.php

Fixes a bug where an existing badge (like "modified") was destroyed in unversioned, translated data objects

addFluentBadge should return existing badge

---

src/Dev/FluentTestState.php

Fixes an issue with Unit tests not clearing the Locale cache properly.
This covers the situation when Unit test 1 populates the locale cache and Unit test 2 uses following setup:
```
protected function setUp()
{
FluentState::singleton()->withState(function (FluentState $state): void {
$state->setLocale('<some_locale>');
parent::setUp();
});
}
```
Note that wrapping `setUp` inside fluent state is really handy for unit tests that require all objects defined in the fixtures to use only one locale.
https://github.com/tractorcow-farm/silverstripe-fluent/issues/591

Fluent dev state fix

---

src/Extension/FluentVersionedExtension.php

Scenario: You have a data object that's both versioned and localised. Let's say that locales available are en_US and nl_NL. You first save english, and after some time, dutch version. Later, somewhere it the code you want to get latest version of that data object.
Expected behaviour: Depending of the locale set in FluentState, you will get latest version written in that locale.
Actual behaviour: if latest version is written in same locale which is set, you will get it. Otherwise returns false.
Or, following example above, if locale is set to nl_NL, you'll get the latest version. If it's en_US - no luck - since there is a version after it, but in different locale.
This PR addresses that issue and makes Versioned return latest version in requested locale, no matter if there are any newer …

Latest version issue fix

---

src/Forms/CopyLocaleAction.php

* `CopyLocaleAction` component is created as many times as there are locales available, see code snippet below (from `FluentExtension`):
```
foreach (Locale::getCached() as $locale) {
$config->addComponents([
new CopyLocaleAction($locale->Locale, true),
new CopyLocaleAction($locale->Locale, false),
]);
}
```
* these components have slightly different UI but they all subscribe to the same action
* whenever either `copy to` or` copy from` action is executed, all of the components will execute the action
* this change-set fixes this by adding additional condition to make the components aware of the locale they are responsible for
https://github.com/tractorcow-farm/silverstripe-fluent/issues/624

Redundant copy locale actions fix (alpha 5).

---

src/Forms/CopyLocaleAction.php

* adds useful extension points for the `copy locale` action
* no functional changes otherwise
* very useful for dealing with special handling of related objects which are localised by relation (indirectly), most notable example would be `Elemental`
https://github.com/tractorcow-farm/silverstripe-fluent/issues/626

Copy locale action extension points.

---

src/Extension/FluentExtension.php
src/Extension/FluentSiteTreeExtension.php
src/Extension/FluentVersionedExtension.php
src/Extension/Traits/FluentAdminTrait.php
src/Extension/Traits/FluentBadgeTrait.php
src/Model/RecordLocale.php
src/View/FluentTemplateGlobalProvider.php
tests/php/Extension/FluentBadgeExtensionTest.php
tests/php/Extension/FluentSiteTreeExtensionTest.php

These changed can be split into separate pull requests and processed individually.
New configuration options were added.
* Fluent menu batch actions are potentially quite destructive and may not be needed in some projects
* added an option to disable this menu (menu is enabled by default)
* following actions are not shown if the menu is disabled batch unlocalise, batch localise, batch unpublish, batch publish, batch archive
* copy content from one locale to another can be achieved by either action and this may be confusing for the content authors (simplicity over flexibility)
* this new configuration allows the developer to choose which actions are desired
* both actions are enabled by default (previous behaviour)
These change are related to how we name things.
* `isLive` - refers to an …

NEW: Localisation manager UI improvements.

---

_config/model.yml
src/Extension/FluentExtension.php
tests/php/Extension/FluentSiteTreeExtensionTest.php
tests/php/Model/Delete/Fixtures/LocalisedRecord.php

No functional change, it's just always bugged me that I didn't really call this config the correct name. Given that we're moving to a major version, now seems like the time to update the name.
I'm not entirely sold on `cms_localisation_required` either... `backend_localisation_required`, maybe?
This config never required "publishing" for the object to be displayed in the CMS, it required "localisation".
I think the feature is still useful in certain situations. EG: For one of our projects we have a Model that is 100% managed through a 3rd party system (we just consume the data). There is no data fallback allowed for these Models, they must be localised in a Locale to be available. This config means that we can easily hide these Models in all interfaces (Model Admin, Dropdown fields, etc) …

v5: Rename cms publish required config

---

src/Extension/FluentSiteTreeExtension.php

* `Modified` site tree flag is no longer displayed for locales without content
* `No source` site tree flag to indicate the situation that page is localised in some other locale but current locale doesn't inherit content from it

Site Tree status flags localised.

---

src/Middleware/DetectLocaleMiddleware.php
src/Middleware/InitStateMiddleware.php
src/State/FluentState.php

This will prevent Director::test() mutating the state
Ensure that FluentState::withState() backs up i18n locale also
Fixes #642

Wrap middleware state mutations inside state helpers

---

lang/sl.yml

New translation to Slovenian (translation is also available in https://www.transifex.com/silverstripe/silverstripe-fluent/).

Translation to Slovenian (sl.yml)

---

_config/cms.yml
docs/en/configuration.md
src/Extension/FluentCMSMainExtension.php
src/Extension/FluentSiteTreeExtension.php
src/Extension/FluentVersionedExtension.php
tests/php/Extension/FluentSiteTreeExtensionTest.php
tests/php/Extension/FluentVersionedExtensionTest.php

Impacted versions: `5.x-dev`
* These are follow up changes to https://github.com/tractorcow-farm/silverstripe-fluent/pull/639
* Stages differ in locale did not cover all cases correctly, this change corrects the behaviour and increases unit test coverage
* Restore action display corrected (Restore action is displayed only when it's relevant)
* Copy-to localise buttons brought back (they were removed in https://github.com/tractorcow-farm/silverstripe-fluent/pull/639 but they still have valid use cases, feedback given in https://github.com/tractorcow-farm/silverstripe-fluent/pull/669)
These buttons are now back and they can be turned on and off:

BUG: Versioned related fixes

---

src/Extension/FluentSiteTreeExtension.php

Augment Localisation tab with clickable locale links to allow easy navigation between page localisations.
This feature is applied to only page via `FluentSiteTreeExtension`.

NEW: Clickable links on page info for localisation tab.

---

src/Extension/FluentVersionedExtension.php

When you navigate to version history viewer you get an exception from the MySQL query as `$localisedVersionTable` is a string that looks like `"SiteTree_Localised_Versions"` which means it currently then becomes `""SiteTree_Localised_Versions""`

Bugfix for version history viewer

---

_config/routing.yml
src/Middleware/LocaleSwitchRedirector.php

E.g. when viewing a record (that may only be valid in one locale), if you change the locale dropdown, you could sometimes end up on a 404 page.
`That record was not found`
This middleware will detect those errors and safely redirect the user to the main admin page instead.
I've opted not to do this on the frontend because it could interfere with any custom home page routing the dev could have built.

ENHANCEMENT 404 errors when changing locales will redirect to the home page of the CMS

---

src/Extension/FluentExtension.php
src/Extension/FluentSiteTreeExtension.php
src/Extension/Traits/FluentAdminTrait.php

* `localise_actions_enabled` setting moved down to FluentExtension and now applied to all buttons UI cases (model, versioned model, site tree model)
* information panel enhancements moved to `FluentAdminTrait` so it's shared with versioned model
* save and delete action UI enhancements now also apply to versioned models

BUG: GridField buttons UI improvements for versioned models.

---

_config/model.yml
docs/en/configuration.md
docs/en/deletion-policies.md
docs/en/scenarios.md
src/Extension/FluentExtension.php
src/Extension/FluentSiteTreeExtension.php
src/Model/RecordLocale.php
tests/php/Extension/FluentSiteTreeExtensionTest.php
tests/php/Extension/FluentSiteTreeExtensionTest.yml
tests/php/Model/Delete/Fixtures/LocalisedRecord.php

* Fallback option added to both `cms_localisation_required` and `frontend_publish_required`
* `cms_publish_required` removed as it's deprecated
* change is not backwards compatible but transition is possible (mapping below):
`false` -> `any`
`true` -> `exact`
Implementation of https://github.com/tractorcow-farm/silverstripe-fluent/issues/705

NEW: Locale fallback configuration enhancement.

---

_config/model.yml
docs/en/configuration.md
src/Extension/FluentDateTimeExtension.php
src/Model/LocalDateTime.php
src/Model/Locale.php
tests/php/Model/LocalDateTimeTest.php
tests/php/Model/LocaleTest.yml

Helpful for when a date needs to be shown in different timezones in any region.
Since DBDatetime doesn't internally support a timezone, we rely on storage in the server timezone, and only convert on rendering output. (otherwise, internal functions like strtotime are wrong).

Feature: Allow timezones to be specified for each region

---

src/Extension/FluentVersionedExtension.php

I noticed that some JOIN operation on version tables can be slow on large DB size type projects.
There are at least two cases where this is notable:
* [Version joins](https://github.com/tractorcow-farm/silverstripe-fluent/blob/master/src/Extension/FluentVersionedExtension.php#L425)
* Cleanup / lookups of versions where join through multiple tables is needed
This change adds the needed indexes.
* Should this be a configuration API variable instead to allow more control over this?

BUG: Missing version tables related indexes.

---

src/Extension/FluentExtension.php

@mfendeksilverstripe these are the suggested changes I had in mind to follow up to #717
I switched out some of the logic in your loopy for checks / queries that were already handled in RecordLocale.
getLocaleInstances was also simplified slightly by re-using this logic.
I have another PR coming up (will take some time to progress) that adjusts the internal storage for localisations to use the localeID

Consolidate some redundant logic in code

---

src/Extension/FluentSiteTreeExtension.php

Allow for usage with headless front end frameworks where you might not always want the locale url segment prepended to the link

feat(site tree extension): add option to disable locale prepend to link

---

lang/it.yml

Locale is seldom used in Italian and can generate confusion into general public, so it has been exchanged for "Lingua" that means "Language" in English.

Italian translation

---

src/Extension/FluentSiteTreeExtension.php

* Now using CMS edit link instead of current URL as the latter can change in some situations like AJAX requests
Fix for https://github.com/tractorcow-farm/silverstripe-fluent/issues/740

BUG: Localisation manager / Locale link fix for AJAX requests.

---

src/Extension/FluentExtension.php
src/Forms/CopyLocaleAction.php
src/Service/CopyToLocaleService.php

It turns out that copy to locale feature is really good! This enhancement contains no functional changes but it opens this feature to be used via public API. This is useful in situations where GridField UI is not appropriate solution like migrations, custom UI or similar.
* generic API is available via a service
* `FluentExtension` provides a simplified API intended for the most common case

NEW: Copy to locale enhancements.

---

src/Extension/FluentVersionedExtension.php
src/Model/RecordLocale.php

* BUG: `FluentVersionedExtension:stagesDifferInLocale()` now uses provided `$locale` and falls back to current locale instead of using current locale in all cases
*  BUG: `RecordLocale:: IsPublished()` corrected - removed legacy base record check and now checks the published state of the source locale instead
* ENH: `updateRecordLocaleStagesDiffer` extension point added to provide some customisation options
Tests are passing on my local.

BUG: Localisation manager fixes

---

src/Extension/FluentExtension.php
src/Forms/BaseAction.php
src/Forms/CopyLocaleAction.php
src/Forms/GroupActionMenu.php
src/Forms/PublishAction.php
src/Forms/UnpublishAction.php

* copy to locale action now respects individual locale permissions
* publish action now respects individual locale permissions
* un-publish action now respects individual locale permissions
User with access to only a single locale.
No change for user with access to all locales.
Tests passing on my local.

NEW: More granular permissions for GridField actions.

---

.github/workflows/main.yml

Most recent version includes a security enhancement to treat input strings as env variables rather than string substitution
After merging this should be merged up to the `4` branch

MNT Bump CI version

---

src/Extension/Traits/FluentAdminTrait.php

Copy 'Locale' to other locales now writes to every locale. I think this is unnecessary and in some cases causes bugs.
Now skipping the original locale.

BUG Fix copyFluent action writing all locales including original

---

src/Extension/FluentFilteredExtension.php
src/Extension/Traits/FluentObjectTrait.php
src/Model/Locale.php

* **Performance**: All instances of `Locale::get()` replaced with `Locale::getCached()` to take advantage of in-memory cache
* **Extensibility**: [Cachable model injection point](https://github.com/tractorcow-farm/silverstripe-fluent/blob/master/src/Model/CachableModel.php#L25) now covers all locale calls which allows consistency in case this is used to customise cached locales data
* **Cleanup**: In-memory cache for locale code lookup removed as this was already operating on top of another memory cache (cached models), the performance gain is negligible and is not worth keeping the additional complexity, also this in-memory cache was not flushed between unit tests and could interfere with [Cachable model injection point](https://github.com/tractorcow-farm/silverstripe-fluent/blob/master/s …

NEW: Locale performance / extensibility enhancements.

---

src/Model/Locale.php

I attempted to reproduce https://github.com/tractorcow-farm/silverstripe-fluent/issues/751 but I had a few problems getting the same symptoms.
In any case, I fixed the permissions code so that the locale-permissions no longer get set to readonly if you check "all cms permissions".

fix: issue with "all cms sections" permission erroneously handling fluent permissions

---

.github/workflows/main.yml

Use v0.1 version of the ci.yml file, which is a special version of the workflow that is re-released whenever a new tag matching 0.1.x is created.  Effectively simulates ^ caret support for github workflows which do not support carets.

MNT Use v0.1 of ci workflow (4 branch)

---

.github/workflows/main.yml

Use v0.1 version of the ci.yml file, which is a special version of the workflow that is re-released whenever a new tag matching 0.1.x is created.  Effectively simulates ^ caret support for github workflows which do not support carets.

MNT Use v0.1 of ci workflow (4.6 branch)

---

.github/workflows/ci.yml
.scrutinizer.yml
composer.json
tests/php/Extension/FluentAdminTraitTest.php
tests/php/Extension/FluentBadgeExtensionTest.php
tests/php/Extension/FluentDirectorExtensionTest.php
tests/php/Extension/FluentExtensionTest.php
tests/php/Extension/FluentFilteredExtensionTest.php
tests/php/Extension/FluentSiteTreeExtensionTest.php
tests/php/Extension/FluentVersionedExtensionTest.php
tests/php/Middleware/DetectLocaleMiddlewareTest.php
tests/php/Model/Delete/DeleteRecordPolicyTest.php
tests/php/Model/LocalDateTimeTest.php
tests/php/Model/LocaleTest.php

NEW: Github workflows setup.
* attempt to make the unit tests run again
Scope of this PR is to only re-enable test suite. Raised a separate issue for [PHP 8 compatibility](https://github.com/tractorcow-farm/silverstripe-fluent/issues/757).

NEW: Github workflows setup.

---

src/Model/Locale.php

Fix for https://github.com/tractorcow-farm/silverstripe-fluent/issues/759
Looks like this issue is caused by the log message which is shown during dev/build when legacy permissions are migrated.

BUG: Legacy permissions migration fix.

---

src/Control/LocaleAdmin.php
src/Extension/FluentDirectorExtension.php
src/Extension/FluentExtension.php
src/Extension/FluentFilteredExtension.php
src/Extension/FluentSiteTreeExtension.php
src/Extension/FluentVersionedExtension.php
src/Middleware/InitStateMiddleware.php
src/Model/CachableModel.php
src/Model/Locale.php
src/Search/FluentSearchForm.php
src/State/BrowserLocaleDetector.php
src/Task/ConvertTranslatableTask.php
tests/php/Extension/FluentDirectorExtensionTest.php
tests/php/Extension/FluentSiteTreeExtensionTest.php
tests/php/Middleware/Stub/DetectLocaleMiddlewareSpy.php

Issue https://github.com/silverstripe/silverstripe-framework/issues/10250

ENH PHP 8.1 compatibility

---

.github/workflows/main.yml
_config.php
composer.json
phpcs.xml.dist
src/Extension/FluentBadgeExtension.php
src/Extension/FluentExtension.php

Also updated to use the new gha-ci instead of the old experimental one
Because we're using `Deprecation::withNoReplacement()` this cannot be used with framework < 4.13
- https://github.com/silverstripeltd/product-issues/issues/666

API Deprecate API removed in fluent 5

---

_config.php
src/Extension/FluentExtension.php

Standardises deprecation notices to be the same as other supported modules
After merging this PR, it should be merged up to or cherry-picked into the `6` branch.
- https://github.com/silverstripeltd/product-issues/issues/666

API Standardise deprecations

---

src/Extension/FluentExtension.php

This is a fix for both https://github.com/symbiote/silverstripe-gridfieldextensions/issues/356 and possibly https://github.com/tractorcow-farm/silverstripe-fluent/issues/257

skip empty 'where' clauses

---

readme.md

- https://github.com/silverstripe/.github/issues/20

DOC Update README.md for CMS 5

---

src/Extension/FluentExtension.php
src/Middleware/InitStateMiddleware.php
tests/php/Middleware/InitStateMiddlewareTest.php

I don't think there's ever a scenario where you'd _want_ to consider previews as not frontend so I don't think this is a breaking change.
I'm on the fence about whether `updatePreviewLink()` belongs here or in `FluentExtension` directly. _Probably_ it belongs on `FluentExtension` so it can affect anything else which have a preview (e.g. elemental blocks which aren't inline-editable) - but I'll leave it like this for now (it is still an improvement and solves the specific exact scenario mentioned in the issue) until someone opines.
- https://github.com/tractorcow-farm/silverstripe-fluent/issues/775

FIX Don't try to preview unlocalised objects

---

src/Extension/FluentExtension.php
src/Extension/FluentVersionedExtension.php

onAfterDuplicate method is now overwritten in FluentVersionedExtension.

Implement onAfterDuplicate

---

templates/Wilr/GoogleSitemaps/Control/GoogleSitemapController_sitemap.ss

align with original template https://github.com/wilr/silverstripe-googlesitemaps/blob/main/templates/Wilr/GoogleSitemaps/Control/GoogleSitemapController_sitemap.ss
without this, it doesn't work in ss5
it may even require some further work down the road:
https://github.com/wilr/silverstripe-googlesitemaps/commit/81b8d870a453abad0858859113bd07dcf42a4447

fix stylesheet path

---

src/Extension/FluentVersionedExtension.php

This part of code is preventing SS5 to be run on MSSQL database.
Fix for #813

MSSQL database doesn't allow aliases in GROUP BY

---

src/Extension/FluentExtension.php

I just copied the bugfix from this PR  #793 which solves issue from this issue: https://github.com/symbiote/silverstripe-gridfieldextensions/issues/356  to Version 6.0.

copy Bugfix for GridFieldAddExistingSearchButton from master to version 6.0

---

src/Extension/FluentCMSMainExtension.php
src/Extension/FluentChangesExtension.php
src/Extension/FluentDateTimeExtension.php
src/Extension/FluentDirectorExtension.php
src/Extension/FluentExtension.php
src/Extension/FluentFilteredExtension.php
src/Extension/FluentGridFieldExtension.php
src/Extension/FluentIsolatedExtension.php
src/Extension/FluentLeftAndMainExtension.php
src/Extension/FluentMemberExtension.php
src/Extension/FluentReadVersionsExtension.php
src/Extension/FluentSiteTreeExtension.php
src/Extension/FluentVersionedExtension.php
src/Extension/Traits/FluentBadgeTrait.php
src/Extension/Traits/FluentObjectTrait.php
src/Forms/CopyLocaleAction.php
src/Forms/VisibleLocalesColumn.php
src/Middleware/DetectLocaleMiddleware.php
src/Model/CachableModel.php
src/Model/Delete/UsesDeletePolicy.php
src/Model/Domain.php
src/Model/Locale.php
src/Model/RecordLocale.php
src/State/BrowserLocaleDetector.php
src/Task/ConvertTranslatableTask.php
src/Task/InitialPageLocalisationTask.php

- Add generic types where appropriate, e.g. for indicating the type of records inside DataList or ArrayList.
- Replace `@property` annotation for extension $owner property with a generic extension. This works effectively the same way, with the bonus benefit that the return type for getOwner() is also correct.
- Remove unnecessary `@var` comments.
Requires https://github.com/silverstripe/silverstripe-framework/pull/11108 for these generics to take effect.
You can validate that the types are evaluating correctly in your preferred code editor.
- https://github.com/silverstripe/silverstripe-framework/issues/11066
- See [picking the right version](https://docs.silverstripe.org/en/contributing/code/#picking-the-right-version)
- Small amounts of additional linting are usually okay, but if it …

ENH Add generic types

---

.github/workflows/dispatch-ci.yml
.github/workflows/update-js.yml
composer.json
phpstan.neon.dist
src/Extension/FluentFilteredExtension.php
src/Model/Domain.php
src/Model/Locale.php

This pull-request was created automatically by [module-standardiser](https://github.com/silverstripe/module-standardiser)

MNT Run module-standardiser

---

src/Extension/Traits/FluentAdminTrait.php
src/Extension/Traits/FluentBadgeTrait.php
src/Extension/Traits/FluentObjectTrait.php

fixes #823 - The magic constant __TRAIT__ was inserting namespaces into localization keys, containing slashes that could not be parsed by the TextCollector task. These have been replaced w/ the Trait name as a string
Run `/dev/tasks/i18nTextCollectorTask` with the environment set to Dev or error reporting otherwise configured to display warnings.
#823

FIX allows i18nTextCollector to concatenate keys
