- .travis.yml
- code/extensions/FluentExtension.php
- tests/FluentTest.php
> BUG Fix creation of records in non-default locale

- code/extensions/FluentExtension.php
- code/tasks/ConvertTranslatableTask.php
> adding space

- code/Fluent.php
- code/extensions/FluentContentController.php
- code/extensions/FluentOldPageRedirectFix.php
- code/routing/FluentRootURLController.php
- code/routing/FluentSession.php
- code/search/FluentMySQLSearch.php
- code/search/FluentSearchAdapter.php
- code/tasks/ConvertTranslatableException.php
- code/tasks/ConvertTranslatableTask.php
> remove trailing spaces in the codebase

- code/Fluent.php
- code/extensions/FluentSiteTree.php
- code/routing/FluentRootURLController.php
Nothing crazy here - but w=1 should display some minor adjustments (removing two unneeded lines and adding two phpdoc blocks)
> turning spaces in tabs and adding some phpdoc blocks

- .travis.yml
- code/extensions/FluentExtension.php
- composer.json
API Bump up minimum version to 3.2.0
> API Take advantage of parameterised queries

- docs/en/configuration.md
- docs/en/domain-configuration.md
In order to help prevent the noise I recently caused on #171 I propose some changes to the documentation which might help new users to better understand the structure of the config file in the case of multiple domains.
> extend domain-configuration.md

- docs/en/configuration.md
- docs/en/dataobjects.md
- docs/en/domain-configuration.md
- docs/en/how-fluent-works.md
- docs/en/installation.md
- docs/en/translatable.md
* Consistency in formatting and spelling
* Added documentation for adding Fluent to extensions (resolves #196)
> Documentation improvements

- code/extensions/FluentExtension.php
- javascript/fluent.js
* Support inputs and textareas (resolves #198)
* Decode JSON from an HTML attribute before parsing it
> [#198] Visual indicator: fix for textareas

- _config/fluent.yml
- code/Fluent.php
- code/extensions/FluentSiteTree.php
- docs/en/configuration.md
- tests/FluentTest.php
Fixes #109
@robbieaverill Do you want to test this feature out?
> API Enable the default locale to omit the prefix

- javascript/fluent.js
Allowing locale switcher to maintain correct highlighted default when using browser navigation.
> FIX: Fixes #211 

- code/extensions/FluentFilteredExtension.php
- composer.json
I removed the variable (const FILTER_ADMIN) as it wasn't fitting the regular SS programming style. Also the class is taking Fluent.FilterAdmin key from config file and adding its value to the queryParams as this wasn't actually working.
> UPDATE: Fluent.FilterAdmin is now taken from config

- code/Fluent.php
Fixes #218
@tony13tv please check this fixes your issue.
> BUG Don't assume default_locale on home page if detect_locale is enabled

- code/extensions/FluentExtension.php
- docs/en/configuration.md
- tests/FluentTest.php
Fixes #156
A long, long requested feature.
> API Support nullable fields

- code/extensions/FluentExtension.php
> FIX Unset index on manipulation no longer causes error

- docs/en/dataobjects.md
> FIX Typo in Extensions section of DataObjects documentation

- code/Fluent.php
- tests/FluentTest.php
> Add ability to force a return value for "is_frontend"

- code/tasks/FluentValidateTask.php
- docs/en/configuration.md
- tests/FluentValidateTaskTest.php
> API Add tests for incorrectly applied extensions

- lang/de.yml
Just a basic language file for german
> german language file

- code/extensions/FluentSiteTree.php
> Fix virtualpage MenuTitle

- lang/fi.yml
This is a very quick translation and not the best possible quality, but at least it's something :). If anybody wants to make any changes to any of the translated terms, please feel free to do it! :)
> Create a Finnish translation

- src/Extension/FluentExtension.php
- src/Extension/FluentVersionedExtension.php
Just some small suggestions to refactor a couple of methods that were quite big. This will hopefully help with readability and testability.
> MINOR Small logic refactor in FluentVersionedExtension and FluentExtension for single use and readability

- src/Extension/FluentExtension.php
- src/Extension/FluentVersionedExtension.php
For the attention of @robbieaverill ;
This pull request implements logging of version updates to SiteTree_Localised_Versions, and supports publishing to SiteTree_Localised_Live
I've refactored most of FluentExtension in such a way that versioning didn't have to repeat much work. :)
> Implement versioned writes

- .travis.yml
- src/Extension/FluentDirectorExtension.php
- src/Extension/FluentExtension.php
- src/Extension/FluentSiteTreeExtension.php
- src/Extension/FluentVersionedExtension.php
- src/Middleware/DetectLocaleMiddleware.php
- src/Model/Domain.php
- src/Model/Locale.php
- tests/php/Middleware/DetectLocaleMiddlewareTest.yml
- tests/php/Model/LocaleTest.php
- tests/php/Model/LocaleTest.yml
Improve Locale / Domain API
Implements changes from https://github.com/tractorcow/silverstripe-fluent/pull/271
> Update link handling

- composer.json
- src/Extension/FluentExtension.php
- src/Model/Locale.php
- templates/FluentSiteTree_MetaTags.ss
- templates/FluentSitemapController_sitemap.ss
- templates/LocaleMenu.ss
Depends on https://github.com/symbiote/silverstripe-gridfieldextensions/pull/213 (merge gridfield PR first)
> Update templates and shift to using inline-editable

- src/Extension/FluentExtension.php
Uses a simpler replacement mechanism than 3.x; Use COALESCE rather than CASE ... WHERE for better performance.
> API Implement localised conditions

- src/Model/Locale.php
- tests/php/Model/LocaleTest.php
> NEW Check "global default" for the first locale when creating

- src/Model/Locale.php
> FIX Do not include the current locale in the list of fallback options

- .travis.yml
I wasn't sure which branch to do this against, but develop and master are both affected
> Update travis install steps

- src/Extension/FluentExtension.php
- tests/php/Extension/FluentExtensionTest.php
- tests/php/Extension/FluentExtensionTest/LocalisedAnother.php
- tests/php/Extension/FluentExtensionTest/LocalisedChild.php
- tests/php/Extension/FluentExtensionTest/LocalisedParent.php
- tests/php/Extension/FluentExtensionTest/UnlocalisedChild.php
> Individual fields whitelisting option added.

- src/Middleware/InitStateMiddleware.php
- tests/php/Middleware/InitStateMiddlewareTest.php
> FIX Do not treat CMS preview requests as frontend

- lang/en.yml
- src/Extension/FluentFilteredExtension.php
- tests/php/Extension/FluentFilteredExtensionTest.php
- tests/php/Extension/FluentFilteredExtensionTest.yml
- tests/php/Extension/FluentSiteTreeExtensionTest.yml
- tests/php/Extension/FluentVersionedExtensionTest.yml
From a feature POV this is complete (if anyone could please give me some feedback), but I've unfortunately run out of time today to write the unit tests, so I will leave this as WIP until I can do that.
---
In combination with the new ability to disable`frontend_publish_required`, this `Extension` attempts to add an additional layer of customisation so that any given Page can be specifically shown or hidden on the front-end for a specific Locale.
I have the following Locales for my site:
* International
* Australia
* United States
* Japan
I create a new record (EG: a `Page`) which I want the International and Australian Locales to inherit the content for when displaying on the frontend. Within the "Filtered Locales" tab of the edit form I add these`Locales` to the `GridField`.
By default, …
> Added new FluentFilteredExtension

- composer.json
> Adjust dependencies

- src/Control/LocaleAdmin.php
> change ModelAdmin icon to SilverStripe font version

- src/Model/Domain.php
- src/Model/FallbackLocale.php
- src/Model/Locale.php
> ENHANCEMENT Add missing extend('updateCMSFields')

- src/Extension/FluentDirectorExtension.php
Replaces #329 and eliminates hard-coding of controller classes in fluent.
> ENHANCEMENT Allow developers to override route controllers

- src/Extension/FluentSiteTreeExtension.php
- tests/php/Extension/FluentSiteTreeExtensionTest.php
- tests/php/Extension/FluentSiteTreeExtensionTest.yml
> FIX Set locale domain or base URL, and URL segment for locale as a page's URL segment

- docs/en/configuration.md
- docs/en/dataobjects.md
- docs/en/installation.md
> DOCS Add explicit notes about using fluent with versioned DataObjects with example config

- src/Extension/FluentExtension.php
> Fix bug: removing the entire table.

- docs/en/configuration.md
- src/Model/Locale.php
Added docs for `frontend_publish_required`.
Updated `Fallbacks` docblock.
> Added docs for frontend_publish_required. Updated Locale docblock

- docs/en/scenarios.md
- readme.md
Just trying to collate some of the things that we've found useful so far. There is so more, but they're a little less simple to document - hopefully I can work on those a little later.
> Added some scenarios to documentation

- _config.php
- src/Extension/FluentExtension.php
> ENHANCEMENT Allow frontend publish filter to be disabled via yml

- src/Extension/FluentVersionedExtension.php
Request to /admin/pages/treeview fails with "sitetree_localised" relation not found on postgres. 
This PR quotes everything to make work.
> Quote table and fields in isLocalisedInStage for postgres compatibility

- src/Middleware/DetectLocaleMiddleware.php
- src/State/FluentState.php
Fixes #419 
Merge up to 4.1 and so on after merge.
> BUG Fix invalid locale being set for domain mode

- src/State/FluentState.php
Fixes #423
Not actually sure if this fixes the error, but need @derralf to please confirm.
If this doesn't fix the error please debug what `var_dump($locale);` is returning.
> BUG Don't fail on empty locale

- src/Extension/FluentExtension.php
The existing logic would always change a record when it is saved. The updated logic checks for a valid current locale and that the record doesn't already exist in the current locale before forcing change on it.
Also if the record isn't versioned then we always force a change.
Doing some testing with this change now but it appears to fix the issue.
Fixes https://github.com/silverstripe/cwp/issues/102
> FIX Only force change for written records when not in current locale, or not versioned

- src/Extension/FluentDirectorExtension.php
- tests/php/Extension/FluentDirectorExtensionTest.php
- tests/php/Extension/FluentDirectorExtensionTest.yml
* added support for multi-byte characters in locale url segments
> Multi-byte characters in URLs are now supported.

- src/Extension/FluentDirectorExtension.php
Fixes https://github.com/tractorcow/silverstripe-fluent/issues/439
> [FIX] Ensure the default locale is set correctly for domain based configuration

- templates/Wilr/GoogleSitemaps/Control/GoogleSitemapController_sitemap.ss
Fixing issue #455
This time from an own branch and targeting 4.1
Again, sorry for the inconvenience.
> Fix bad xml in GoogleSitemapController_sitemap.ss

- lang/en.yml
- src/Model/Locale.php
Issue: https://github.com/silverstripe/silverstripe-framework/issues/8356
> FIX Text collector translations now compile without errors

- src/Extension/FluentVersionedExtension.php
- tests/php/Extension/FluentVersionedExtensionTest.php
even when a page does not exist in that locale
> existsInLocale() returns true when hitting the cache

- src/Extension/FluentExtension.php
I have two Locales:
- International (en_NZ)
- Australia (en_AU)
I have a basic `DataObject` structure.
`BaseDeal extends DataObject`
`SystemDeal extends BaseDeal`
`FluentVersionedExtension` has been applied to `BaseDeal`.
`BaseDeal` has a bunch of localised fields.
`SystemDeal` does **not** contain any localised fields (and it doesn't need to).
When you archive a `SystemDeal` from **any** Locale, the record will become unavailable in **all** Locales.
`FluentExtension::updateDeleteTables()` does not consider the existence of a base record when performing `$rootDelete->execute()` on an unlocalised table.
```
// If table isn't localised, simple delete
if (!isset($localisedTables[$table])) {
$rootDelete->execute();
continue;
}
```
Join with the base table (when the current table is **not** …
> BUGFIX: Only delete unlocalised table record when no base record exists.

- src/Extension/FluentSiteTreeExtension.php
Issue: https://github.com/tractorcow-farm/silverstripe-fluent/issues/496
> add alternate links to metatags

- src/Extension/FluentVersionedExtension.php
> FIX Quoting Locale filter correctly for PostgreSQL

- src/Search/FluentSearchVariant.php
Fix for https://github.com/tractorcow-farm/silverstripe-fluent/issues/497
> fix index when fluent is in use and there is no fallback locale

- src/Extension/FluentVersionedExtension.php
This was added in https://github.com/silverstripe/silverstripe-versioned/commit/2a065b20a742e4d427d0a26a44f4ab9c12c9c084 in SilverStripe 4.4
> FIX Add support for 'latest_version_single' versioned mode

- docs/en/state.md
> DOCS Describe how to mutate state programatically

- docs/en/deletion-policies.md
> DOCS document delete policy

- src/Extension/FluentExtension.php
> BUG Warn during dev/build if fluent extension is applied wrong

- src/Middleware/DetectLocaleMiddleware.php
Let http-only cookies be configurable, but default to secure
Fixes #534
> BUG Don't use unsecure cookies if session is secure

- docs/en/configuration.md
- src/Search/FluentSearchForm.php
Add search extension to enable using SS Core search functionality with Fluent.
> Add SS Core Fluent search extension

- src/Model/Delete/DeleteRecordPolicy.php
Fixes #570
note: This is a critical fix, and once this is tagged (4.4.4) everyone on an older 4.4 version must upgrade immediately.
> BUG Fix issue with localisations being randomly deleted

- docs/en/scenarios.md
Hello @tractorcow,
just a minor update of the documentation to fix missing class (FluentHelper) and adding use-statements in. Just trying to make it easier. Let me know if you think it's need anything else.
Cheers,
Peter
> MINOR: update of example in scenarios

- CONTRIBUTING.md
- readme.md
Closes https://github.com/tractorcow-farm/silverstripe-fluent/issues/587
cc @chillu
> Update contributing guidelines

- _config/model.yml
- docs/en/configuration.md
- src/Control/LocaleAdmin.php
- src/Extension/FluentExtension.php
- src/Extension/FluentIsolatedExtension.php
- src/Extension/Traits/FluentBadgeTrait.php
- src/Extension/Traits/FluentObjectTrait.php
- src/Model/Locale.php
- src/Model/RecordLocale.php
- templates/FluentSiteTree_MetaTags.ss
- templates/LocaleMenu.ss
- templates/Wilr/GoogleSitemaps/Control/GoogleSitemapController_sitemap.ss
- tests/php/Extension/FluentSiteTreeExtensionTest.php
- Add FluentIsolatedExtension (objects that belong in one locale only)
- Add support for `x-default` hreflang
- Bugfixes for badges and saving localised dataobjects
> Additional 5.0 alpha features

- _config/model.yml
> Prevent duplicate siteconfigs when localised

- src/Extension/FluentVersionedExtension.php
Reverts tractorcow-farm/silverstripe-fluent#597
Fixes #600
> Revert "Latest version issue fix"

- lang/de.yml
- src/Extension/Traits/FluentAdminTrait.php
- src/Extension/Traits/FluentBadgeTrait.php
- src/Extension/Traits/FluentObjectTrait.php
- replace magic var `__CLASS__` with `__TRAIT__` in traits
- added de.yml
> Translations

- docs/en/configuration.md
- docs/en/locale-detection.md
- readme.md
- src/Dev/FluentTestState.php
- src/Model/Domain.php
- src/Model/Locale.php
- src/State/BrowserLocaleDetector.php
- src/State/CloudflareLocaleDetector.php
- tests/php/State/CloudflareLocaleDetectorTest.php
- tests/php/State/CloudflareLocaleDetectorTest.yml
Users can setup https://support.cloudflare.com/hc/en-us/articles/200168236-Configuring-Cloudflare-IP-Geolocation to use ip detection via cloudflare
> Update locale detection to include cloudflare logic

- src/Extension/FluentMemberExtension.php
> BUG fix issue with member permissions erroring before fluent state is initialised

- src/Extension/FluentExtension.php
Fixes https://github.com/tractorcow-farm/silverstripe-fluent/issues/633
> Source locale lookup correction.

- docs/en/configuration.md
Added documentation on recommended encoding settings and known issues.
> Encoding configuration documentation.

- src/Extension/FluentDirectorExtension.php
FIxes #645
cc @bumbus does this fix your issue?
> BUG Resolve regression in middleware behaviour breaking routing bootstrapping

- src/Extension/FluentDirectorExtension.php
https://github.com/tractorcow-farm/silverstripe-fluent/issues/654
> Added extension point to FluentDirectorExtension

- .travis.yml
- composer.json
- phpcs.xml.dist
- tests/php/Extension/FluentExtensionTest.php
> MNT Use travis shared config, use sminnee/phpunit

- .travis.yml
- src/Extension/FluentVersionedExtension.php
* Fix Travis setup to run with correct requirements to match composer requirements
* Fix breaking unit tests
> BUG: Fix Travis setup to run with correct requirements.

- src/Model/Locale.php
> Add missing CRUD permissions for Locale dataobject

- src/Extension/FluentExtension.php
- tests/php/Extension/FluentExtensionTest.php
- tests/php/Extension/FluentExtensionTest/TestModel.php
- tests/php/Extension/FluentExtensionTest/TestRelationPage.php
Fix for https://github.com/tractorcow-farm/silverstripe-fluent/issues/713
> BUG: Localised copy support for ClassName changes.

- src/Model/Locale.php
See https://github.com/tractorcow-farm/silverstripe-fluent/issues/737
> Fix fallback locales chain

- composer.json
- tests/php/Extension/FluentAdminTraitTest.php
- tests/php/Extension/FluentBadgeExtensionTest.php
- tests/php/Extension/FluentDirectorExtensionTest.php
- tests/php/Extension/FluentExtensionTest.php
- tests/php/Extension/FluentFilteredExtensionTest.php
- tests/php/Extension/FluentSiteTreeExtensionTest.php
- tests/php/Extension/FluentVersionedExtensionTest.php
- tests/php/Middleware/DetectLocaleMiddlewareTest.php
- tests/php/Model/Delete/DeleteRecordPolicyTest.php
- tests/php/Model/LocalDateTimeTest.php
- tests/php/Model/LocaleTest.php
> BUG: PHP 8 compatibility patch.

- lang/en.yml
Had "you" rather than "to" to introduce the infinitive "to make".
> Minor grammatical correction

- lang/da.yml
- lang/de.yml
- lang/ru.yml
Issue https://github.com/silverstripe/.github/issues/14
> ENH Update translations

- package.json
- yarn.lock
Issue https://github.com/silverstripe/silverstripe-admin/issues/1436
> MNT Update dev JS

- src/Extension/FluentVersionedExtension.php
- src/Model/Locale.php
Resolves #792
You can now use `$CurrentLocale.AbsoluteBaseURL` in your template as necessary.
> feat: add absolute base url for locales

- lang/es.yml
- lang/nl.yml
Automated translations update generated using [silverstripe/tx-translator](https://github.com/silverstripe/silverstripe-tx-translator)
> TLN Update translations
